var annotated_dup =
[
    [ "ucc_coll_args", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s.html#structucc__coll__args", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s_structucc__coll__args" ],
    [ "ucc_coll_args.dst", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s.html#unionucc__coll__args_8dst", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s_unionucc__coll__args_8dst" ],
    [ "ucc_coll_args.src", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s.html#unionucc__coll__args_8src", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s_unionucc__coll__args_8src" ],
    [ "ucc_coll_buffer_info", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s___d_t.html#structucc__coll__buffer__info", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s___d_t_structucc__coll__buffer__info" ],
    [ "ucc_coll_buffer_info_v", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s___d_t.html#structucc__coll__buffer__info__v", "group___u_c_c___c_o_l_l_e_c_t_i_v_e_s___d_t_structucc__coll__buffer__info__v" ],
    [ "ucc_coll_callback", "structucc__coll__callback.html", "structucc__coll__callback" ],
    [ "ucc_coll_req", "namespace_3global_scope_4.html#structucc__coll__req", "namespace_3global_scope_4_structucc__coll__req" ],
    [ "ucc_context_attr", "group___u_c_c___c_o_n_t_e_x_t___d_t.html#structucc__context__attr", "group___u_c_c___c_o_n_t_e_x_t___d_t_structucc__context__attr" ],
    [ "ucc_context_params", "group___u_c_c___c_o_n_t_e_x_t___d_t.html#structucc__context__params", "group___u_c_c___c_o_n_t_e_x_t___d_t_structucc__context__params" ],
    [ "ucc_ee_params", "group___u_c_c___e_v_e_n_t___d_t.html#structucc__ee__params", "group___u_c_c___e_v_e_n_t___d_t_structucc__ee__params" ],
    [ "ucc_ep_map_array", "group___u_c_c___t_e_a_m___d_t.html#structucc__ep__map__array", "group___u_c_c___t_e_a_m___d_t_structucc__ep__map__array" ],
    [ "ucc_ep_map_cb", "structucc__ep__map__cb.html", "structucc__ep__map__cb" ],
    [ "ucc_ep_map_strided", "group___u_c_c___t_e_a_m___d_t.html#structucc__ep__map__strided", "group___u_c_c___t_e_a_m___d_t_structucc__ep__map__strided" ],
    [ "ucc_ep_map_t", "group___u_c_c___t_e_a_m___d_t.html#structucc__ep__map__t", "group___u_c_c___t_e_a_m___d_t_structucc__ep__map__t" ],
    [ "ucc_ep_map_t.__unnamed2__", "group___u_c_c___t_e_a_m___d_t.html#unionucc__ep__map__t_8____unnamed2____", "group___u_c_c___t_e_a_m___d_t_unionucc__ep__map__t_8____unnamed2____" ],
    [ "ucc_event", "group___u_c_c___e_v_e_n_t___d_t.html#structucc__event", "group___u_c_c___e_v_e_n_t___d_t_structucc__event" ],
    [ "ucc_generic_dt_ops", "structucc__generic__dt__ops.html", "structucc__generic__dt__ops" ],
    [ "ucc_generic_dt_ops.reduce", "structucc__generic__dt__ops_8reduce.html", "structucc__generic__dt__ops_8reduce" ],
    [ "ucc_lib_attr", "group___u_c_c___l_i_b___i_n_i_t___d_t.html#structucc__lib__attr", "group___u_c_c___l_i_b___i_n_i_t___d_t_structucc__lib__attr" ],
    [ "ucc_lib_params", "group___u_c_c___l_i_b___i_n_i_t___d_t.html#structucc__lib__params", "group___u_c_c___l_i_b___i_n_i_t___d_t_structucc__lib__params" ],
    [ "ucc_mem_map", "group___u_c_c___c_o_n_t_e_x_t___d_t.html#structucc__mem__map", "group___u_c_c___c_o_n_t_e_x_t___d_t_structucc__mem__map" ],
    [ "ucc_mem_map_params", "group___u_c_c___c_o_n_t_e_x_t___d_t.html#structucc__mem__map__params", "group___u_c_c___c_o_n_t_e_x_t___d_t_structucc__mem__map__params" ],
    [ "ucc_oob_coll", "structucc__oob__coll.html", "structucc__oob__coll" ],
    [ "ucc_reduce_cb_params", "group___u_c_c___d_a_t_a_t_y_p_e.html#structucc__reduce__cb__params", "group___u_c_c___d_a_t_a_t_y_p_e_structucc__reduce__cb__params" ],
    [ "ucc_team_attr", "group___u_c_c___t_e_a_m___d_t.html#structucc__team__attr", "group___u_c_c___t_e_a_m___d_t_structucc__team__attr" ],
    [ "ucc_team_p2p_conn", "structucc__team__p2p__conn.html", "structucc__team__p2p__conn" ],
    [ "ucc_team_params", "group___u_c_c___t_e_a_m___d_t.html#structucc__team__params", "group___u_c_c___t_e_a_m___d_t_structucc__team__params" ]
];